---
defaultBaseImageVersion: latest
properties:
- name: IBMCLOUD_TARGET_REGION
  value: ${BUILD_REGION_ID}
  type: text
- name: IBMCLOUD_TARGET_RESOURCE_GROUP
  value: ${BUILD_RESOURCE_GROUP}
  type: text
- name: BUILD_CLUSTER
  value: ${BUILD_CLUSTER_NAME}
  type: text
- name: BUILD_CLUSTER_NAMESPACE
  value: ${BUILD_CLUSTER_NAMESPACE}
  type: text
- name: IBM_CLOUD_API_KEY
  value: ${API_KEY}
  type: secure
- name: VAULT_INSTANCE
  value: ${VAULT_INSTANCE}
  type: text
stages:
- name: Init Docker Content Trust
  properties:
  - name: REGISTRY_REGION
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: REGISTRY_NAMESPACE
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: IMAGE_NAME
    value: ${APP_NAME}
    type: text
  - name: DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE
    value: ${DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE}
    type: secure
  - name: DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE
    value: ${DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE}
    type: secure
  jobs:
  - name: Create DCT Keys
    type: builder
    curatedDockerImage: default
    artifact_dir: back-your-keys    
    build_type: customimage
    docker_image: jauninb/pbi-docker:latest
    script: |
      #!/bin/bash

      # Get the notary binary
      curl -L https://github.com/theupdateframework/notary/releases/download/v0.6.1/notary-Linux-amd64 -o /usr/local/bin/notary
      # Make it executable
      chmod +x /usr/local/bin/notary

      export IBMCLOUD_API_KEY=$IBM_CLOUD_API_KEY
      export DOCKER_CONTENT_TRUST=1

      # Setup Docker-In-Docker
      source <(curl -s -S -L "https://raw.githubusercontent.com/jauninb/jumpstart/master/setup_dind.sh")

      # configure the container registry
      export REGISTRY_REGION=$(echo "$REGISTRY_REGION" | awk -F ':' '{print $NF;}')
      ibmcloud cr region-set $REGISTRY_REGION
      # login docker to ibm container registry
      ibmcloud cr login

      # check the existence of the container registry namespace
      REGISTRY_URL=$(ibmcloud cr info | grep -m1 -i '^Container Registry' | awk '{print $3;}')
      echo "Check for $REGISTRY_NAMESPACE existence"
      if ibmcloud cr namespaces | tail --lines=+4 | head --lines=-2 | grep "^$REGISTRY_NAMESPACE"; then
        echo "$REGISTRY_NAMESPACE exists in $REGISTRY_URL"
      else 
        echo "Creating REGISTRY_NAMESPACE in $REGISTRY_URL"
        ibmcloud cr namespace-add $REGISTRY_NAMESPACE
      fi

      # Initialize the repository for Docker Content Trust
      echo "Doing Docker Content Trust initialization for GUN $REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME"
      source <(curl -s -S -L "https://raw.githubusercontent.com/jauninb/jumpstart/master/notary_init_gun.sh")

      if [ "$VAULT_INSTANCE" ]; then
        echo "Backing-up keys in $VAULT_INSTANCE"
        # jsonify the Vault access values
        source <(curl -sSL "https://raw.githubusercontent.com/jauninb/jumpstart/master/signatures.sh")
        VAULT_DATA=$(buildVaultAccessDetailsJSON "$VAULT_INSTANCE" "$IBMCLOUD_TARGET_REGION" "$IBMCLOUD_TARGET_RESOURCE_GROUP")

        # remove secrets. start new
        deleteSecret "rootkey" "$VAULT_DATA"
        deleteSecret "repokey" "$VAULT_DATA"
        deleteSecret "builderkey" "$VAULT_DATA"
        deleteSecret "validatorkey" "$VAULT_DATA"
        deleteSecret "DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE" "$VAULT_DATA"
        deleteSecret "DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE" "$VAULT_DATA"

        # save the root, repo pem key files to the Vault
        savePemFileByRoleToVault "root" "rootkey" "$VAULT_DATA"
        savePemFileByRoleToVault "target" "repokey" "$VAULT_DATA"
        # save the root and repo repository passphrases to the Vault
        saveData "DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE" "$VAULT_DATA" "$DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE"
        saveData "DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE" "$VAULT_DATA" "$DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE"
      fi     
- name: Create Build Signer
  inputs:
  - type: job
    stage: Init Docker Content Trust
    job: Create DCT Keys
  triggers:
  - type: stage
  properties:
  - name: DEVOPS_SIGNER
    value: ${BUILD_SIGNER}
    type: text
  - name: dct_properties
    value: dct.properties
    type: file
  jobs:
  - name: Create Build Signer Keys
    type: builder
    curatedDockerImage: default
    artifact_dir: back-your-keys    
    build_type: customimage
    docker_image: jauninb/pbi-docker:latest
    script: |
      #!/bin/bash
      echo "Create signer $DEVOPS_SIGNER for $REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME"

      export IBMCLOUD_API_KEY=$IBM_CLOUD_API_KEY
      export DOCKER_CONTENT_TRUST=1

      # Setup Docker-In-Docker
      source <(curl -s -S -L "https://raw.githubusercontent.com/jauninb/jumpstart/master/setup_dind.sh")

      # configure the container registry
      export REGISTRY_REGION=$(echo "$REGISTRY_REGION" | awk -F ':' '{print $NF;}')
      ibmcloud cr region-set $REGISTRY_REGION
      # login docker to ibm container registry
      ibmcloud cr login

       # Restore  keys
      source <(curl -sSL "https://raw.githubusercontent.com/jauninb/jumpstart/master/signatures.sh")
      VAULT_DATA=$(buildVaultAccessDetailsJSON "$VAULT_INSTANCE" "$IBMCLOUD_TARGET_REGION" "$IBMCLOUD_TARGET_RESOURCE_GROUP")
      #write repo pem file to trust/private
      writeFile "$(readData "repokey" "$VAULT_DATA")"
      export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$(readData "DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE" "$VAULT_DATA")
      # Create the new signer key
      source <(curl -s -S -L "https://raw.githubusercontent.com/jauninb/jumpstart/master/create_dct_signer_key.sh")
      #save the new signer pem key to the Vault
      savePemFileByRoleToVault "$DEVOPS_SIGNER" "$DEVOPS_SIGNER" "$VAULT_DATA"
- name: Create Validation Signer
  inputs:
  - type: job
    stage: Create Build Signer
    job: Create Build Signer Keys
  triggers:
  - type: stage
  properties:
  - name: DEVOPS_SIGNER
    value: ${VALIDATION_SIGNER}
    type: text
  - name: dct_properties
    value: dct.properties
    type: file
  jobs:
  - name: Create Validation Signer Keys
    type: builder
    curatedDockerImage: default
    artifact_dir: back-your-keys    
    build_type: customimage
    docker_image: jauninb/pbi-docker:latest
    script: |
      #!/bin/bash
      echo "Create signer $DEVOPS_SIGNER for $REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME"

      export IBMCLOUD_API_KEY=$IBM_CLOUD_API_KEY
      export DOCKER_CONTENT_TRUST=1

      # Setup Docker-In-Docker
      source <(curl -s -S -L "https://raw.githubusercontent.com/jauninb/jumpstart/master/setup_dind.sh")

      # configure the container registry
      export REGISTRY_REGION=$(echo "$REGISTRY_REGION" | awk -F ':' '{print $NF;}')
      ibmcloud cr region-set $REGISTRY_REGION
      # login docker to ibm container registry
      ibmcloud cr login

      # Restore  keys
      source <(curl -sSL "https://raw.githubusercontent.com/jauninb/jumpstart/master/signatures.sh")
      VAULT_DATA=$(buildVaultAccessDetailsJSON "$VAULT_INSTANCE" "$IBMCLOUD_TARGET_REGION" "$IBMCLOUD_TARGET_RESOURCE_GROUP")
      #write repo pem file to trust/private
      writeFile "$(readData "repokey" "$VAULT_DATA")"
      export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$(readData "DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE" "$VAULT_DATA")
      # Create the new signer key
      source <(curl -s -S -L "https://raw.githubusercontent.com/jauninb/jumpstart/master/create_dct_signer_key.sh")
      #Save the signer private key
      savePemFileByRoleToVault "$DEVOPS_SIGNER" "$DEVOPS_SIGNER" "$VAULT_DATA"
      
- name: Setup IKS Runtime enforcement in deployment cluster
  inputs:
  - type: job
    stage: Create Validation Signer
    job: Create Validation Signer Keys
  triggers:
  - type: stage
    enabled: false
  properties:
  - name: DEFAULT_HELM_VERSION
    value: 2.13.1
    type: text
  - name: dct_properties
    value: dct.properties
    type: file
  - name: CLUSTER_NAMESPACE
    value: ${PROD_CLUSTER_NAMESPACE}
    type: text
  jobs:
  - name: Create CISE CRD and Secret
    type: deployer
    curatedDockerImage: default
    deploy_type: kubernetes
    target:
      region_id: ${PROD_REGION_ID}
      api_key: ${API_KEY}
      resource_group: ${PROD_RESOURCE_GROUP}
      kubernetes_cluster: ${PROD_CLUSTER_NAME}
    script: |
      #!/bin/bash
      #set -x

      source <(curl -s -S -L "https://raw.githubusercontent.com/jauninb/jumpstart/master/check_helm_up_and_running.sh")

      # Install CISE
      if helm list cise | grep '^cise'; then
        echo "Container Image Security Enforcement is already installed"
      else
        helm repo add iks-charts https://icr.io/helm/iks-charts
        helm install --name cise iks-charts/ibmcloud-image-enforcement
      fi

      # Define custom user policies
      echo "Create CISE custom policies"
      for signer_and_key in $(cat dct_signers.json | jq -r -c '.[] | {name:.Name, key: .Keys[0].ID}'); do
        DEVOPS_SIGNER=$(echo $signer_and_key | jq -r '.name')
        DEVOPS_SIGNER_PRIVATE_KEY=$(echo $signer_and_key | jq -r '.key')

        source <(curl -s -S -L "https://raw.githubusercontent.com/jauninb/jumpstart/master/create_cise_crd.sh")
        createCISE_CRD | tee cise_crd_custom_policy.yaml

        echo " "
        echo "Applying CISE custom policy to $CLUSTER_NAMESPACE"
        kubectl apply -f cise_crd_custom_policy.yaml -n$CLUSTER_NAMESPACE

        echo "Creating Secret $REGISTRY_NAMESPACE.$IMAGE_NAME.$DEVOPS_SIGNER to provide public key"
        # ensure the secret is not already existing
        kubectl delete secret "$REGISTRY_NAMESPACE.$IMAGE_NAME.$DEVOPS_SIGNER" -n$CLUSTER_NAMESPACE \
          --ignore-not-found=true
        kubectl create secret generic "$REGISTRY_NAMESPACE.$IMAGE_NAME.$DEVOPS_SIGNER" -n$CLUSTER_NAMESPACE \
          --from-literal=name=$DEVOPS_SIGNER \
          --from-file=publicKey=$DEVOPS_SIGNER.pub
      done
